name: TEST
on:
  push:
    branches:
    - master

env:
  # This is a base repository and we use ${GITHUB_SHA} to set the version of the container
  REPO: docker.pkg.github.com/promaty/actions-test/img

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: >
        docker login docker.pkg.github.com
        -u $GITHUB_ACTOR
        -p ${{ secrets.GITHUB_TOKEN }}
    # use previously built image for cache if possible
    - run: docker images
    - run: docker pull docker.pkg.github.com/promaty/actions-test/img:latest
    - run: docker images
    - run: docker build . -t tst -t docker.pkg.github.com/promaty/actions-test/img:latest --cache-from docker.pkg.github.com/promaty/actions-test/img:latest
    - run: docker push docker.pkg.github.com/promaty/actions-test/img:latest


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   # no way to read ca.crt from environment variable
  #   - run: echo ${{ secrets.KUBE_CA }} | base64 -d > ca.crt
  #   - run: |
  #       kubectl config set-cluster aragon --server=${{ secrets.KUBE_SERVER }} --certificate-authority=ca.crt
  #       kubectl config set-credentials aragon --token=$(base64 -d <<< ${{ secrets.KUBE_TOKEN }})
  #       kubectl config set-context aragon --cluster=aragon --user=aragon
  #       kubectl config use-context aragon
  #   - run: kubectl set image deployment/court-backend-rinkeby server=$REPO:${GITHUB_SHA}
  #   - run: kubectl set image deployment/court-backend-rinkeby services=$REPO:${GITHUB_SHA}
  #   - run: kubectl set image deployment/court-backend-rinkeby app=$REPO:${GITHUB_SHA}
  #   # wait 60 seconds for the new pod to be ready. If the pod is not ready there is a problem with the new container
  #   - run: kubectl wait pod -l app=court-backend-rinkeby --for condition=Ready --timeout=60s
